### ISSUE TITLE
关于第二章中部分问题反馈

### ISSUE THREAD

**Issue by konghen123** [datawhalechina/fantastic-matplotlib#1]
1.在第二章中2.Patch下的2) bar-柱状图部分：
有一行代码是：
plt.bar(np.arange(16), y, alpha=0.5, width=0.5, color='yellow', edgecolor='red', label='The First Bar', lw=3);
可以看到这里设置了label为The First Bar，如果直接运行原代码是不会有label显示的，需在最后加上一句plt.legend()

2.针对1. 2DLines下，2) errorbar绘制误差折线图的部分，在plt.errorbar（）有很多可以设置的参数，这里笔者可以在基础代码上加上一些参数的设置，可以让例子更生动，比如：
plt.errorbar(x,y+3,yerr=yerr,fmt='o',ecolor='r',color='b',elinewidth=2,capsize=4);
plt.errorbar(x,y,yerr=error_range,fmt='o:',ecolor='hotpink',elinewidth=3,ms=5,mfc='salmon',capsize=3)

**Comment by skywateryang** [comment]
1. 由于图例legend命令在第四章会重点讲述，故在本章不展开，避免混乱
2. 该建议已在教程中更新
