### ISSUE TITLE
关于第4part的内容补充

### ISSUE THREAD

**Issue by zhangZZZ-v** [datawhalechina/fantastic-matplotlib#2]
【1】坐标：二.Tick上的文本--b) Tick Locators
问题：对locator=plt.MaxNLocator(nbins=7)的解释没有，建议加上对plt.MaxNLocator（nbins=m）的解释，“选择合适的位置并不超过m个间隔”。在下面的例子中，建议把nbins=10改为nbins=3，这样对比其他locator的效果会更清晰一点。

【2】坐标：二.Tick上的文本--matplotlib.dates 模块
问题：没有写明导入mdates和datetime模块，个人认为对新手不是很友好，特别是mdates这种被as过的。建议加上
import matplotlib.dates as mdates
import datetime

**Comment by skywateryang** [comment]
感谢反馈
【1】教程中已更新
【2】每一章所有用到的库都在章节最上方统一引入
